server:
	rm -rf out/
	ant
	cd out; java ServerMain

client:
	rm -rf out/
	ant
	cd out; java ClienteEmissorMain

alojador:
	rm -rf out/
	ant
	cd out; java AlojadorMain

distribuicao:
	rm -rf out/
	ant
	cd out; java CentroDistribuicaoMain
